<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cuci_tangan_model extends CI_Model
{

    public $table = 'cuci_tangan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function unit()
    {
        
        return $this->db->get('unit')->result();
    }
    function moment()
    {
        
        return $this->db->get('moment')->result();
    }
     function mutu()
    {
        
        return $this->db->get('list_indikator')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nm', $q);
	$this->db->or_like('profesi', $q);
	$this->db->or_like('unit', $q);
	$this->db->or_like('kesempatan', $q);
	$this->db->or_like('cucitangan', $q);
	$this->db->or_like('ketcuci', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('moment', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nm', $q);
	$this->db->or_like('profesi', $q);
	$this->db->or_like('unit', $q);
	$this->db->or_like('kesempatan', $q);
	$this->db->or_like('cucitangan', $q);
	$this->db->or_like('ketcuci', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('moment', $q);
	$this->db->limit($limit, $start);
    $this->db->join('unit', 'unit.id_unit = cuci_tangan.unit');
    $this->db->join('moment', 'moment.id_moment = cuci_tangan.moment');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Cuci_tangan_model.php */
/* Location: ./application/models/Cuci_tangan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-13 01:30:14 */
/* http://harviacode.com */