<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_inventaris_model extends CI_Model
{

    public $table = 'data_inventaris';
    public $id = 'id_inven';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_inven', $q);
	$this->db->or_like('kode_inven', $q);
	$this->db->or_like('nm_barang', $q);
	$this->db->or_like('merek', $q);
	$this->db->or_like('tipe', $q);
	$this->db->or_like('sn', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('kondisi', $q);
	$this->db->or_like('id_ruang', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('stts', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_inven', $q);
	$this->db->or_like('kode_inven', $q);
	$this->db->or_like('nm_barang', $q);
	$this->db->or_like('merek', $q);
	$this->db->or_like('tipe', $q);
	$this->db->or_like('sn', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('kondisi', $q);
	$this->db->or_like('id_ruang', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('stts', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_inventaris_model.php */
/* Location: ./application/models/Data_inventaris_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2026-08-06 13:21:49 */
/* http://harviacode.com */