<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ikp_model extends CI_Model
{

    public $table = 'ikp';
    public $id = 'tgl_kejadian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ikp', $q);
	$this->db->or_like('nm_pasien', $q);
	$this->db->or_like('rm', $q);
	$this->db->or_like('ruang', $q);
	$this->db->or_like('kelamin', $q);
	$this->db->or_like('penangung_jawab', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->or_like('jam_masuk', $q);
	$this->db->or_like('tgl_kejadian', $q);
	$this->db->or_like('jam_kejadian', $q);
	$this->db->or_like('insiden', $q);
	$this->db->or_like('krologis', $q);
	$this->db->or_like('jns_insiden', $q);
	$this->db->or_like('pelapor_pertama', $q);
	$this->db->or_like('insiden_terjadipd', $q);
	$this->db->or_like('insiden_meyangkut', $q);
	$this->db->or_like('tempat_insiden', $q);
	$this->db->or_like('insiden_terjadipd2', $q);
	$this->db->or_like('unit_penyebab', $q);
	$this->db->or_like('akibat_insiden', $q);
	$this->db->or_like('tindakan', $q);
	$this->db->or_like('tindakan_oleh', $q);
	$this->db->or_like('kejadian_terulang', $q);
	$this->db->or_like('ket_kejadian_terulang', $q);
	$this->db->or_like('pelapor', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('tgl_lapor', $q);
	$this->db->or_like('grading_resiko', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ikp', $q);
	$this->db->or_like('nm_pasien', $q);
	$this->db->or_like('rm', $q);
	$this->db->or_like('ruang', $q);
	$this->db->or_like('kelamin', $q);
	$this->db->or_like('penangung_jawab', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->or_like('jam_masuk', $q);
	$this->db->or_like('tgl_kejadian', $q);
	$this->db->or_like('jam_kejadian', $q);
	$this->db->or_like('insiden', $q);
	$this->db->or_like('krologis', $q);
	$this->db->or_like('jns_insiden', $q);
	$this->db->or_like('pelapor_pertama', $q);
	$this->db->or_like('insiden_terjadipd', $q);
	$this->db->or_like('insiden_meyangkut', $q);
	$this->db->or_like('tempat_insiden', $q);
	$this->db->or_like('insiden_terjadipd2', $q);
	$this->db->or_like('unit_penyebab', $q);
	$this->db->or_like('akibat_insiden', $q);
	$this->db->or_like('tindakan', $q);
	$this->db->or_like('tindakan_oleh', $q);
	$this->db->or_like('kejadian_terulang', $q);
	$this->db->or_like('ket_kejadian_terulang', $q);
	$this->db->or_like('pelapor', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('tgl_lapor', $q);
	$this->db->or_like('grading_resiko', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ikp_model.php */
/* Location: ./application/models/Ikp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-16 03:23:02 */
/* http://harviacode.com */