<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class List_indikator_model extends CI_Model
{

    public $table = 'list_indikator';
    public $id = 'id_indikator';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    // $allowed_indikators: NULL = tanpa batasan (admin/direktur); array id_indikator = hanya itu
    function get_all($allowed_indikators = NULL)
    {
        $this->db->select('list_indikator.*, unit.nm_unit');
        $this->db->from($this->table);
        $this->db->join('unit', 'unit.id_unit = list_indikator.id_unit', 'left');
        $this->_apply_scope($allowed_indikators);
        $this->db->order_by('list_indikator.' . $this->id, $this->order);
        return $this->db->get()->result();
    }

    /**
     * Batasi data sesuai akses indikator per user (tabel user_list_indikator).
     * - $allowed_indikators === NULL : tanpa batasan (admin/direktur).
     * - array berisi id_indikator : hanya indikator tsb.
     * - array kosong : tidak ada indikator yang boleh dilihat.
     */
    private function _apply_scope($allowed_indikators = NULL)
    {
        if ($allowed_indikators === NULL) {
            return;
        }
        if (!empty($allowed_indikators)) {
            $this->db->where_in('list_indikator.id_indikator', $allowed_indikators);
        } else {
            $this->db->where('1 = 0', NULL, FALSE);
        }
    }

    // Pencarian pada kolom teks (termasuk nama unit)
    private function _apply_search($q = NULL)
    {
        if ($q === NULL || $q === '') {
            return;
        }
        $this->db->group_start();
        $this->db->like('list_indikator.id_indikator', $q);
        $this->db->or_like('list_indikator.kelompok', $q);
        $this->db->or_like('list_indikator.jenis', $q);
        $this->db->or_like('list_indikator.judul', $q);
        $this->db->or_like('unit.nm_unit', $q);
        $this->db->group_end();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('list_indikator.*, unit.nm_unit');
        $this->db->from($this->table);
        $this->db->join('unit', 'unit.id_unit = list_indikator.id_unit', 'left');
        $this->db->where('list_indikator.' . $this->id, $id);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL, $allowed_indikators = NULL) {
        $this->db->from($this->table);
        $this->db->join('unit', 'unit.id_unit = list_indikator.id_unit', 'left');
        $this->_apply_scope($allowed_indikators);
        $this->_apply_search($q);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $allowed_indikators = NULL) {
        $this->db->select('list_indikator.*, unit.nm_unit');
        $this->db->from($this->table);
        $this->db->join('unit', 'unit.id_unit = list_indikator.id_unit', 'left');
        $this->_apply_scope($allowed_indikators);
        $this->_apply_search($q);
        $this->db->order_by('list_indikator.' . $this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
     function users()
    {
        
        return $this->db->get('users')->result();
    }

    // daftar unit untuk dropdown form indikator
    function units()
    {
        return $this->db->where('status', 'aktif')->order_by('nm_unit', 'ASC')->get('unit')->result();
    }

}

/* End of file List_indikator_model.php */
/* Location: ./application/models/List_indikator_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-07 01:29:01 */
/* http://harviacode.com */