<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mutu_indikator_model extends CI_Model
{

    public $table = 'mutu_indikator';
    public $id = 'id_mutu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL,$idindikator) {
     $this->db->where('id_indikator', $idindikator);
     $this->db->group_start();
    $this->db->like('id_mutu', $q);
	$this->db->or_like('tanggal', $q);
// 	$this->db->or_like('id_indikator', $q);
	$this->db->or_like('num', $q);
	$this->db->or_like('demu', $q);
	$this->db->group_end();
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $idindikator) {
        $this->db->order_by('tanggal', $this->order);
        $this->db->where('id_indikator', $idindikator);
        $this->db->group_start();
        $this->db->like('id_mutu', $q);
    	$this->db->or_like('tanggal', $q);
    	$this->db->or_like('num', $q);
    	$this->db->or_like('demu', $q);
    	$this->db->group_end();
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // ================= VALIDASI =================

    // daftar user untuk pilihan validator
    function users()
    {
        return $this->db->order_by('name', 'ASC')->get('users')->result();
    }

    // riwayat validasi per indikator (join nama validator + data mutu)
    function get_validasi($id_indikator)
    {
        $this->db->select('mv.*, u.name AS nama_validator, mu.tanggal AS mutu_tanggal, mu.num AS mutu_num, mu.demu AS mutu_demu, mu.id_mutu AS mutu_id');
        $this->db->from('mutu_validasi mv');
        $this->db->join('users u', 'u.id = mv.userid', 'left');
        $this->db->join('mutu_indikator mu', 'mu.id_mutu = mv.id_mutu', 'left');
        $this->db->where('mv.id_indikator', $id_indikator);
        $this->db->order_by('mv.tanggal_awal', 'DESC');
        $this->db->order_by('mv.id_validasi', 'DESC');
        return $this->db->get()->result();
    }

    function get_validasi_by_id($id)
    {
        $this->db->select('mv.*, u.name AS nama_validator, mu.tanggal AS mutu_tanggal, mu.num AS mutu_num, mu.demu AS mutu_demu');
        $this->db->from('mutu_validasi mv');
        $this->db->join('users u', 'u.id = mv.userid', 'left');
        $this->db->join('mutu_indikator mu', 'mu.id_mutu = mv.id_mutu', 'left');
        $this->db->where('mv.id_validasi', $id);
        return $this->db->get()->row();
    }

    function insert_validasi($data)
    {
        $this->db->insert('mutu_validasi', $data);
        return $this->db->insert_id();
    }

    function delete_validasi($id)
    {
        $this->db->where('id_validasi', $id);
        $this->db->delete('mutu_validasi');
    }

    // data mutu dalam rentang tanggal (untuk detail validasi per periode)
    function get_in_range($id_indikator, $awal, $akhir)
    {
        $this->db->where('id_indikator', (int) $id_indikator);
        $this->db->where('tanggal >=', $awal);
        $this->db->where('tanggal <=', $akhir);
        $this->db->order_by('tanggal', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // jumlah num & denum dalam rentang tanggal (untuk isi otomatis form validasi)
    function sum_range($id_indikator, $awal = NULL, $akhir = NULL)
    {
        $this->db->select('IFNULL(SUM(num),0) AS num, IFNULL(SUM(demu),0) AS demu', FALSE);
        $this->db->where('id_indikator', (int) $id_indikator);
        if ($awal !== NULL && $awal !== '') {
            $this->db->where('tanggal >=', $awal);
        }
        if ($akhir !== NULL && $akhir !== '') {
            $this->db->where('tanggal <=', $akhir);
        }
        $row = $this->db->get($this->table)->row();
        return array(
            'num'  => $row ? (float) $row->num : 0,
            'demu' => $row ? (float) $row->demu : 0,
        );
    }

}

/* End of file Mutu_indikator_model.php */
/* Location: ./application/models/Mutu_indikator_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-07 02:04:16 */
/* http://harviacode.com */