<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sertifikat_peserta_model extends CI_Model
{

    public $table = 'sertifikat_peserta';
    public $id = 'id_peserta';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_allfilter($id)
    {
         $this->db->where('id_sertifikat', $id);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL,$idsertifikat) {
        $this->db->where('id_sertifikat', $idsertifikat);
     $this->db->group_start();
     $this->db->like('id_peserta', $q);
	$this->db->or_like('nm_peserta', $q);
	$this->db->or_like('no_peserta', $q);
	$this->db->group_end();
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL,$idsertifikat) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('id_sertifikat', $idsertifikat);
     $this->db->group_start();
     $this->db->like('id_peserta', $q);
	$this->db->or_like('nm_peserta', $q);
	$this->db->or_like('no_peserta', $q);
	$this->db->group_end();
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sertifikat_peserta_model.php */
/* Location: ./application/models/Sertifikat_peserta_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-21 09:34:49 */
/* http://harviacode.com */